name: deploy

run-name: Deploy to GH Pages

on:
  push:
    branches:
      - "**/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build up git commit short SHA
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Download dependencies from cache if present
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Download dependencies if needed
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build the distribution bundle
        run: yarn build

      - name: Compress distribution bundle
        run: cd build && tar -czvf ${{ github.sha }}.tar.gz ./

      - name: Archive release artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: ${{ github.sha }}.tar.gz
          if-no-files-found: error
    
  deploy:
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1