name: deploy

run-name: Deploy to GH Pages

on:
  push:
    branches:
      - "**/**"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    
  deploy:
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1