name: deploy

run-name: Deploy to GH Pages

on:
  push:
    branches:
      - "**/**"

jobs:
  deploy:
    needs: deploy
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/build.yaml
