name: deploy

run-name: Deploy to development

on:
  push:
    branches:
      - "chore/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Download dependencies from cache if present
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Download dependencies
        run: yarn --frozen-lockfile

      - name: Build the distribution bundle
        run: yarn build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: release-bundle
          path: build/

  deploy:
    needs: build
    runs-on: "ubuntu-latest"

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: development
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          preview: true
          artifact_name: "release-bundle"
